version: "3"

services:
  app:
    # image: php:7.2-apache
    build:
      context: ./docker/app
      dockerfile: DockerFile
    networks:
      - appnet
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7.16
    networks:
      - appnet
    volumes:
      - ./docker/db/mysql_data:/var/lib/mysql
      - ./docker/db/my.cnf:/ect/mysql/conf.d/my.conf
    restart: always
    env_file:
      - ./docker/db/db-variable.env
    # environment:
    #   MYSQL_ROOT_PASSWORD: rootpassword
    #   MYSQL_DATABASE: appdb
    #   MYSQL_USER: appuser
    #   MYSQL_PASSWORD: password

networks:
  appnet:

volumes:
  app-db-volume:
